<?php

echo 'Heavy: Ya-da-da-da-da-da- It is good day to be not dead!';
echo '<br><br>';
echo 'Engineer: POW! You are dead!';
echo '<br><br>';
echo 'Heavy: I am dead!';
echo '<br><br>';
echo 'Engineer: Chuckling, while spy is doing the conga towards the scene (The Engineer says aw, shucks” as the Spy gets close.)';
echo '<br><br>';
echo 'Spy: Oh! The Heavy is dead!';
echo '<br><br>';
echo 'Heavy: Yes (Sandwich). I am dead!';
echo '<br><br>';
echo 'Spy: Why is the Heavy dead?!';
echo '<br><br>';
echo 'Engineer: I dunno.';
echo '<br><br>';
echo 'Heavy: I think it was-';
echo '<br><br>';
echo 'Engineer & Spy: Shhh, you are dead!';
echo '<br><br>';
echo 'Heavy: Ok.';
echo '<br><br>';
echo '(Sniper enters scene exiting van)';
echo '<br><br>';
echo "Sniper: What's up, you wankers?! Who’s up for a- AH! What the- bloody hell just happened?!";
echo '<br><br>';
echo 'Engineer & Spy: The Heavy is dead!';
echo '<br><br>';
echo '(A, B, C, or D game starts)';
echo '<br><br>';
echo 'Sniper: The Heavy is dead!';
echo '<br><br>';
echo 'Spy: Correct!';
echo '<br><br>';
echo '(Option C lights up and celebration music starts playing)';
echo '<br><br>';
echo 'Spy: So, did you see the murderer?';
echo '<br><br>';
echo 'Engineer and Sniper: Nah, sorry mate.';
echo '<br><br>';
echo 'Spy: Slams hand on desk I will find him, I will capture him, and no one will ever die again!';
echo '<br><br>';
echo '(Engineer and Sniper applause)';
echo '<br><br>';
echo "Sniper: Ah, well that's nice.";
echo '<br><br>';
echo 'Engineer: I am damn proud right now.';
echo '<br><br>';
echo '(Soldier appears in scene)';
echo '<br><br>';
echo 'Soldier: Atteeeeeeeeention!';
echo '<br><br>';
echo '(Soldier rushes to dead Heavy)';
echo '<br><br>';
echo 'Soldier: That Heavy is dead!';
echo '<br><br>';
echo 'Spy: We know!';
echo '<br><br>';
echo 'Soldier: Who killed him?!';
echo '<br><br>';
echo 'Spy: We don’t know!';
echo '<br><br>';
echo 'Soldier: I will find clues!';
echo '<br><br>';
echo '(Soldier searches through pile of stuff while sniffing)';
echo '<br><br>';
echo "Soldier: What's that? Grabs gun A weapon?! That thing is why the Heavy is dead!";
echo '<br><br>';
echo 'Engineer, Sniper, and Spy: The Heavy is dead?!';
echo '<br><br>';
echo 'Soldier: Slams hands on desk Yes, (Intense background appears) he died!';
echo '<br><br>';
echo 'Engineer, Sniper, and Spy: All shocked';
echo '<br><br>';
echo '(Intense background stops, showing the Engineer, Sniper, and Spy standing in front of a green screen)';
echo '<br><br>';
echo 'Medic: (From far away) Incoming!';
echo '<br><br>';
echo '(Ambulance crashes Soldier into a building wall, killing him.)';
echo '<br><br>';
echo 'Medic: Exits out of Ambulance Raus, raus! Pushes Engineer, Sniper, and Spy away from Heavy Move now! Kisses Heavy on head';
echo '<br><br>';
echo '(Heavenly music sounds while the light focuses on Heavy)';
echo '<br><br>';
echo 'Heavy: (Rising in air) Hohoho, Hea- Explodes Oof.';
echo '<br><br>';
echo 'Medic: In my medical opinion, that Heavy is dead!';
echo '<br><br>';
echo '(Camera rotates to Sniper)';
echo '<br><br>';
echo 'Sniper: Doc, what happened?';
echo '<br><br>';
echo 'Medic: My professional opinion? Slams hands on desk then turns to the right (Intense background comes in) The Heavy was killed!';
echo '<br><br>';
echo '(Intense background stops)';
echo '<br><br>';
echo 'Engineer, Sniper, and Spy: Panicking';
echo '<br><br>';
echo 'Medic: I don’t think it’s anything to worry about.';
echo '<br><br>';
echo 'Spy: Well, now what?';
echo '<br><br>';
echo '(Scout entering while doing the conga in the background)';
echo '<br><br>';
echo 'Scout: Clipidy clop mother****er! Boom!';
echo '<br><br>';
echo 'Spy: Says “Oh, come on.” before Scout says boom';
echo '<br><br>';
echo 'Scout: Look at this! The freaking Heavy is dead! Pause What do you think of that? Pause Ahm…';
echo '<br><br>';
echo 'Spy: Yes, yes, Scout.';
echo '<br><br>';
echo 'Scout: Yea?';
echo '<br><br>';
echo 'Spy: Go home!';
echo '<br><br>';
echo '(Scout’s mother appears in a car telling Scout to get in)';
echo '<br><br>';
echo 'Scout: Ah come on! Pffff! Freaking unbelievable seriously, you all suck.';
echo '<br><br>';
echo '(Car drives off and crashing noise is heard)';
echo '<br><br>';
echo 'Scout: Screams of pain';
echo '<br><br>';
echo 'Spy: Ok, let’s get back to the point.';
echo '<br><br>';
echo 'Heavy: Poking at his dead body I think Heavy is dead.';
echo '<br><br>';
echo 'Engineer, Sniper, Spy, and Medic: The Heavy is dead?!';
echo '<br><br>';
echo 'Medic: Turns around and notices dead scout in burning car Scout! I will heal you- Car explodes and camera goes back to Heavy';
echo '<br><br>';
echo 'Heavy: Oh, Seriously?! Who killed Heavy?!';
echo '<br><br>';
echo '(Camera shows on Demoman drinking Scrumpy)';
echo '<br><br>';
echo 'Demoman: Slurp Slurp It was me!';
echo '<br><br>';
echo 'Engineer, Sniper, Spy, and Heavy: Shocked';
echo '<br><br>';
echo 'Demoman: Yes! Bottle of Scrumpy slides up Demoman’s body and Demoman eats the bottle I did it like this: Takes out a revolver and shoots Sniper in chest Boom! Demoman flies off from force of revolver blast';
echo '<br><br>';
echo 'Sniper: Screams of pain';
echo '<br><br>';
echo 'Demoman: Woop dee doo!';
echo '<br><br>';
echo 'Engineer, Spy, and Heavy: Are terrified seeing Sniper’s dead body';
echo '<br><br>';
echo 'Demoman: Burps That’s a joke, lads.';
echo '<br><br>';
echo 'Engineer, Spy, and Heavy: Starts laughing like crazy';
echo '<br><br>';
echo 'Demoman: Slurp Slurp Burp It was… yo-... Burp Points at Engineer Him!';
echo '<br><br>';
echo 'Engineer: Shocked How did you know?!';
echo '<br><br>';
echo 'Demoman: I didn’t. Burps That was a joke too.';
echo '<br><br>';
echo '(Camera moves to Engineer, as the Demoman keeps drinking faster)';
echo '<br><br>';
echo 'Demoman: Falls on ground Oh, I’m dead.';
echo '<br><br>';
echo 'Engineer: Manic laughter That’s right! It was me!';
echo '<br><br>';
echo 'Spy: You monster!';
echo '<br><br>';
echo 'Heavy: But whyyyyy?';
echo '<br><br>';
echo 'Engineer: Cause you’re fat, boy. And another thing, you’re ugly.';
echo '<br><br>';
echo 'Heavy: Engineer, stop!';
echo '<br><br>';
echo 'Engineer and Heavy: Arguing';
echo '<br><br>';
echo 'Spy: Shrugs (Text appears saying : IT’S TRADITION)';
echo '<br><br>';
echo 'Engineer: Ah dammit Heavy **** off! You are dead.';
echo '<br><br>';
echo 'Heavy: No u, POW! Haha.';
echo '<br><br>';
echo '(Engineer falls dead on floor)';
echo '<br><br>';
echo 'Heavy: You are dead! Not big surprise.';
echo '<br><br>';
echo 'Spy: Well that was idiotic. Off to hang myself! Spy doing flip on noose Watch and lea- Choking noises';
echo '<br><br>';
echo 'Heavy: I am alive! Is nice. Yes, this is stupid.';

die;

?>